import { Injectable } from '@angular/core';
import { addIcons } from 'ionicons';
import { addCircleOutline, addOutline, albumsOutline, alert, alertCircle, alertCircleOutline, analyticsOutline, arrowBack, arrowForward, arrowForwardOutline, arrowUndo, beerOutline, bookmarkOutline, bugOutline, checkmarkCircle, checkmarkCircleOutline, chevronForward, closeCircle, closeOutline, cloudOutline, createOutline, cubeOutline, documentTextOutline, eyeOutline, fileTrayOutline, gitPullRequest, homeOutline, layersOutline, logoEuro, logOutOutline, navigateCircleOutline, notificationsOutline, peopleOutline, personOutline, phonePortraitOutline, pintOutline, print, printOutline, pulseOutline, radioButtonOff, radioButtonOn, refreshOutline, removeCircle, restaurantOutline, returnDownForwardOutline, rocketOutline, save, searchOutline, send, sendOutline, settingsOutline, shieldCheckmarkOutline, speedometerOutline, star, statsChartOutline, storefrontOutline, tabletLandscapeOutline, timerOutline, trash } from 'ionicons/icons';

@Injectable({
    providedIn: 'root'
})
export class IonIconsService {

    public useDefinedIcons = () => addIcons({
        addCircleOutline,
        addOutline,
        albumsOutline,
        alert,
        alertCircle,
        alertCircleOutline,
        analyticsOutline,
        arrowBack,
        arrowForward,
        arrowForwardOutline,
        arrowUndo,
        beerOutline,
        bookmarkOutline,
        bugOutline,
        checkmarkCircle,
        checkmarkCircleOutline,
        chevronForward,
        closeCircle,
        closeOutline,
        cloudOutline,
        createOutline,
        cubeOutline,
        documentTextOutline,
        eyeOutline,
        fileTrayOutline,
        gitPullRequest,
        homeOutline,
        layersOutline,
        logoEuro,
        logOutOutline,
        navigateCircleOutline,
        notificationsOutline,
        peopleOutline,
        personOutline,
        phonePortraitOutline,
        pintOutline,
        print,
        printOutline,
        pulseOutline,
        radioButtonOff,
        radioButtonOn,
        refreshOutline,
        removeCircle,
        restaurantOutline,
        returnDownForwardOutline,
        rocketOutline,
        save,
        searchOutline,
        send,
        sendOutline,
        settingsOutline,
        shieldCheckmarkOutline,
        speedometerOutline,
        star,
        statsChartOutline,
        storefrontOutline,
        tabletLandscapeOutline,
        timerOutline,
        trash
    });
}
