name: Build App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm ci

      - name: Run Build
        run: npm run ci:build:production

      - name: Upload Debug Artifact
        uses: actions/upload-artifact@v3
        with:
          name: PWA
          path: www

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/download-artifact@v3
        with:
          name: PWA
          path: dist

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: dist
