name: Build App

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm ci

      - name: Run Build
        run: npm run ci:build:production

      - name: Upload Debug Artifact
        uses: actions/upload-artifact@v3
        with:
          name: PWA
          path: www

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download PWA Artifact
        uses: actions/download-artifact@v3
        with:
          name: PWA
          path: dist

      - name: 📂 Upload PWA
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_DEPLOY_HOST }}
          username: ${{ secrets.FTP_DEPLOY_USERNAME }}
          password: ${{ secrets.FTP_DEPLOY_PASSWORD }}
          local-dir: ./dist
          dangerous-clean-slate: true
