name: Build App

on:
  push:
    branches: [feature/*]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install Ionic
        run: npm i -g @ionic/cli

      - name: Install Dependencies
        run: npm ci

      - name: Run Build
        run: npm run ci:build:production

      - name: Upload Debug Artifact
        uses: actions/upload-artifact@v3
        with:
          name: PWA
          path: www

  deploy:
    name: Deploy
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/download-artifact@v3
        with:
          name: PWA
          path: dist

      - name: Deploy via FTP
        uses: JakobVesely/ftp-action-delete-and-upload@master
        with:
          host: ${{ secrets.FTP_DEPLOY_HOST }}
          user: ${{ secrets.FTP_DEPLOY_USERNAME }}
          password: ${{ secrets.FTP_DEPLOY_PASSWORD }}
          localDir: "dist"
          remoteDir: "."
